services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: admin123
    ports:
      - 80:5678
    disks:
      - name: n8n-data
        mountPath: /home/node/.n8n
        sizeGB: 1
